name: Test Refresh Token

on:
  workflow_dispatch:

jobs:
  refresh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Test Refresh Token
        env:
          ANNA_REFRESH_TOKEN: ${{ secrets.ANNA_REFRESH_TOKEN }}
          ANNA_CLIENT_ID: ad-fci
        run: |
          python refresh_test.py
